version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
      # workaround, ver https://github.com/docker/compose/issues/10162
      labels:
        com.docker.compose.container-number: "1"  # workaround de "has invalid com.docker.compose.container-number label:"
    #command: -debug API
    env_file: .env
    volumes:
      - ./config.yml:/app/config.yml
      - ./service-account.json:/app/service-account.json
